kind: pipeline
type: docker
name: ansible-galaxy-publish

steps:
- name: build-and-publish
  image: docker.io/geerlingguy/docker-debian11-ansible
  environment:
    ANSIBLE_GALAXY_TOKEN:
      from_secret: ansible_galaxy_token
  commands:
  - ansible-galaxy collection build --token $ANSIBLE_GALAXY_TOKEN