---


- name: Include best matching instructions based on os family and distribution
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', task_files_lookup) }}"
  vars:
    task_files_lookup:
      paths:
      - "{{ role_path }}/tasks"
      files:
      - "{{ ansible_facts['distribution'] }}_podman_host.yml"
      - "{{ ansible_facts['os_family'] }}_family_podman_host.yml"
